### ISSUE TITLE
How can I get the Calendar.Date in my timezone?

### ISSUE THREAD

**Issue by lachie** [PanagiotisGeorgiadis/Elm-DateTime#2] opened 2019-03-30 00:39 UTC
Hi, thanks for the package, its just what I was looking for.
I have one issue though: I'm not sure that I can get a Calendar.Date for my timezone.

For example if I use `Calendar.fromPosix` now it says that its Friday 29/March/2019. However its definitely Saturday 30/March/2019 where I live.

I'm having to work around this by getting a time, converting to "human time" with the current timezone, then using `fromRawParts`.

Data modeling-wise though, yielding `Maybe Date` doesn't make sense because its definitely 30/March in my timezone.

Essentially I'd like a new function like this:
```
fromZonePosix : Time.Zone -> Time.Posix -> Date
fromZonePosix zone posix =
    Date
        { year = Year (Time.toYear zone posix)
        , month = Time.toMonth zone posix
        , day = Day (Time.toDay zone posix)
        }

-- and so fromPosix becomes
fromPosix : Time.Posix -> Date
fromPosix posix = fromZonePosix Time.utc
```

I'm pretty new to elm, so not sure how to do a PR with adequate tests (how do I run the tests you currently have?) otherwise I'd do a full PR

thanks again
Lachie

**Comment by Erudition** [comment] 2019-04-04 02:17
I agree. The fact that this package can't handle timezones in a simple way doesn't make any sense. It talks about the "overhead" of timezones and daylight savings time (which doesn't even need to be handled separately from the time zones!), but all I see is the need to optionally pass in an additional parameter to each function, the `zone`. Optional, because we could also just pass in `utc` everywhere and use the package as it is right now.

**Comment by PanagiotisGeorgiadis** [comment] 2019-04-04 08:03
Hello everyone and thanks a lot for opening this issue!

I think that initially we were thinking of some issues that may come up with using ***timezones*** ( which I didn't document and can't remember tbh ) but I think I agree with the idea of passing in a `Zone` and constructing the `DateTime` in the given timezone. I will take a look on Friday afternoon - Saturday morning and update the code / tests where necessary. If you are in a hurry or if you feel like, feel free to raise a PR and I may be able to review it earlier in the week. Again, thanks a lot for taking the time to raise the issue and I hope you enjoy using Elm and the package above! :D 

Thanks,
Panagiotis

**Comment by PanagiotisGeorgiadis** [comment] 2019-04-05 18:26
### Elm-DateTime package timezones support:

I’ve given it some thought and I’ve also done some research in order to see if we are able to implement this feature.

Before we get started I would like to apologise for the long message and to add that if I have missed anything please get back to me.

As stated in the [elm/time](https://package.elm-lang.org/packages/elm/time/latest/) package, the ***zoned timestamps should only be used for representation purposes*** and not for storing or modelling. That basically means that in databases and any other types of models we should be using UTC timestamps ( in an ideal world, API’s and applications would “talk” using only UTC timestamps but that’s not always the case ). On that note this package was created in order to transform a `Posix time` into its `Gregorian calendar` form and in order to make it easier for the consumers to manipulate `Dates` ( without taking timezones into consideration ).

When I first saw your comments I didn’t quite remember the reasons we went with this approach and I honestly thought that I missed something so I went back to the “whiteboard” in order to analyse the whole approach and I’ve come up with the following results.

Lets say that we could refactor the `DateTime` package as follows:
```
fromPosix : Time.Zone -> Time.Posix -> DateTime

fromRawParts : Time.Zone -> RawDate -> RawTime -> Maybe DateTime

toPosix : DateTime -> { posix : Time.Posix, zone : Time.Zone }

toMillis : DateTime -> { millis : Int, zone : Time.Zone }
```
*Notice that the `toPosix` and `toMillis` functions would need to return the Time.Zone in order for the user to be able to transform the results into UTC.*

But there are some issues that come up when going more in depth with this approach.

Lets take the case of a consumer who calls `Time.now` and `Time.here` to get their timestamp and timezone respectively. Also the consumer will need to go forward in time ( the same scenario can occur if you go backwards as well ) into the target date of **26th of August 2019 00:00:00** and then get the posix that corresponds to this date.

```
myDate =
    DateTime.fromPosix ( GMT+0000 ) (Time.millisToPosix 1541030400000) — 1st of November 2018 00:00:00

myFutureDate =
    Maybe.andThen (DateTime.setMonth Aug) (DateTime.setDay 26 myDate) — Just (26th of August 2019 00:00:00)

{ posix, zone } =
    DateTime.toPosix myFutureDate

-- posix = 1566777600000 -- 26th of August 2019 00:00:00
-- zone = GMT+0000
```

This would unfortunately be a wrong result ( and a confusing one nevertheless ). First of all, the timestamp above represents the **correct date and time given that the timezone is GMT+0000.**

But in this case the ***26th of August 2019 date belongs to the GMT+0100 timezone*** ( due to daylight saving time ). Also the timestamp above if converted into GMT+0100 would result in **26th of August 01:00:00** which is also 1 hour away from what the consumer anticipated. Overall, the result wouldn't be reliable.

This is caused by ***Daylight Saving Time***. DST basically changes the timezone depending on the area etc. This means that if we were to use timezones with this package we would definitely lose the **isomorphic** concept plus on some occasions we may return wrong results to the consumer which can cause too much overhead.

In my opinion we shouldn’t handle timezones inside this package because our goal is to model `Date` and `Time` and not format them.

Now lets get to @lachie's  issues mentioned above.

- I am assuming you are running **Time.now** in order to get a `Posix` and transform it to a `DateTime`. You would need to add the **timezoneOffset** to the Posix you just got in order for the `DateTime` to match your current `Date` and `Time`. 

I will be adding a `getTimezoneOffset : Time.Zone -> Time.Posix -> Int` function which will return the timezone offset so that you can add it to the **Time.now** `Posix` result which should do the trick.

- The `fromRawParts` constructor results in a `Maybe DateTime` because of the nature of dates. Some examples as for why can be found [here](https://package.elm-lang.org/packages/PanagiotisGeorgiadis/elm-datetime/latest/DateTime#fromRawParts) but it all boils down to date validation. ***One future improvement could be to return a `Result ValidationError DateTime` so that we can give more descriptive information to the consumers as to why the date creation failed.***

You can always use something like in order to convert a `Maybe DateTime` into a `DateTime` but I would advice against it.
```
date =
    Maybe.withDefault (DateTime.fromPosix 0) maybeDate
```

Overall, I don't have the entire scope of your use case but if you would like to share more about the use case you are having I would be more than glad to help.

I hope I've addressed everyone's concerns and I hope that with these examples I've made my train of thought clear. If you believe I got my math wrong anywhere please respond to this issue or raise a new one. 😃

Thanks again for your time,
Panagiotis

**Comment by lachie** [comment] 2019-04-07 01:19
Thanks for taking the time to address the issue. While I understand your reasoning, I have to admit that I find the outcome a bit frustrating. I think the difference is that I'm not using DateTime, only Calendar.

My use case is that I'm writing a calendar program and only want to use the Calendar module.

When I start the program I'm requesting now `Time.here` & `Time.now` via a task, as you guessed, then transforming it
```
nullDate = Calendar.fromPosix (Time.millisToPosix 0)

toCalendarDate : Time.Zone -> Time.Posix -> Date
toCalendarDate zone now =
  let
      rawDate = 
        { day = (Time.toDay zone now)
        , month = (Time.toMonth zone now)
        , year = (Time.toYear zone now)
        }
  in
      (Calendar.fromRawParts rawDate) |> Maybe.withDefault nullDate
```

then I'd like to take today and plan out an entire year: from today to today + 1 year:
```
--- the day before plus a year:
end = (Calendar.incrementYear (Calendar.decrementDay start))
```

If I could use the timezone to get the date at my location I could just do:
```
toCalendarDate : Time.Zone -> Time.Posix -> Date
toCalendarDate = Calendar.fromZoneAndPosix
```

My core problems seem to be:
- I don't care about the timezone. From my model's naive perspective there is no time, only dates. In other words, I want to get from the time that I ask the computer for to a correct date as quickly as possible and then discard the timezone altogether.
- There's no way that the date can be invalid if I derive it from an absolute time & a timezone. I don't want to represent `Maybe Date` in my model because it makes no sense to my program. Currently I'm working around this behaviour by using a `nullDate` which will never be used because the raw date parts I use can never be wrong as its derived from the real `here` and `now`. This workaround feels wrong.
- Although timezones are "presentational" for times, I disagree that they're presentational for dates, or perhaps its that datas are always presentational. It seems to me that this is the core dilemma, but its also one you address in the readme:
> We should note here though, that since the Posix will contain the milliseconds that form both a date and a time, the Calendar.Date will drop all the time related information. If you were to transform a Calendar.Date back to Posix, it would represent the given Date but it will always default on midnight hours, which means that it may lose some of the information provided. We've decided that we will not allow a Calendar.Date to Time.Posix conversion since its not an isomorphic one. You can instead get the milliseconds that represent the given Date and combine them with the milliseconds that represent a given Time.
In other words, its simply not possible to convert from a posix (absolute & location free) time to a date _without_ taking the location on earth into account. If that weren't true it'd seem to me like only dates in the UTC timezone are truly representable.

I guess I don't really see the harm in providing a function
```
fromZoneAndPosix : Time.Zone -> Time.Posix -> Date
fromZoneAndPosix zone posix =
    Date
        { year = Year (Time.toYear zone posix)
        , month = Time.toMonth zone posix
        , day = Day (Time.toDay zone posix)
        }
```
Since converting from posix to a date is lossy and the inverse is already impossible (as stated in the doc), does adding this function really dilute the reasoning you've laid out?

I guess also that `getTimezoneOffset : Time.Zone -> Time.Posix -> Int` will do the trick as you say, but it seems less elegant. What will my code look like?
```
toCalendarDate : Time.Zone -> Time.Posix -> Date
toCalendarDate zone now =
  let
      offset = getTimezoneOffset here now
      posix = (Time.posixToMillis now) + offset
  in
      Calendar.fromPosix posix
```

**Comment by PanagiotisGeorgiadis** [comment] 2019-04-16 17:05
I've released a new version of the package that contains the helper `getTimezoneOffset` function and unfortunately I believe that this is the "safest" way to approach this issue.

Some notes on the core problems that were mentioned above would be:

* Even if your model doesn't take time into perspective it doesn't mean it isn't there. In order to construct a timestamp you would need to account for time ( even if that is set to 00:00:00.000 ). Also in order to get the correct date you would need to also define the "context". The "context" in your case would be your user's timezone since you would like to display the date relative to their location. 

* If you use the `fromRawParts` constructor the resulting `DateTime` will always be wrapped in a `Maybe` because of the nature of the input. Since they are raw parts the could be invalid combinations such as the 29th of February on a non leap year or the 31st of April to name some.

* Timezones can affect dates as well. You've experienced a different **date and time** in your first comment:
> For example if I use Calendar.fromPosix now it says that its Friday 29/March/2019. However its definitely Saturday 30/March/2019 where I live.

* Another example of that scenario would be to take into consideration the date **01/01/2019 10:00:00.000 (GMT + 11)**. If you transform it to UTC ( ie take away the timezone ) it would become **2018-12-31 23:00:00.000 UTC**. As it can be seen from this example, we may even have year / month differences in dates dependent on the specified timezone and the given timestamp.

Overall, I think that at least for now you would have to use the `toCalendarDate` implementation mentioned above in order to get the today's date on your timezone ( or on the user's timezone to be more exact ). I hope that with the newly added function you will be able to advance in building your app and that the `DateTime` package will make your date handling a lot easier :)

I will be closing this issue since I don't think I have to contribute more information on the topic as of now but feel free to open a new one if you encounter any other issues :)

Once more thanks a lot for taking the time to raise this issue!

Panagiotis

**Closed as completed** 2019-04-24 14:04 UTC
